### ISSUE TITLE
[!] name 'logger' is not defined

### ISSUE THREAD

**Issue by Mojo8898** [ShutdownRepo/pywhisker#21]
Error still persists when executing from pipx OR git clone.

From pipx:

```
pywhisker -d example.com -u example_user -p example_pass --target example_target --action add

Traceback (most recent call last):
  File "/home/kali/.local/share/pipx/venvs/pywhisker/lib/python3.12/site-packages/pywhisker/pywhisker.py", line 819, in main
    shadowcreds = ShadowCredentials(ldap_server, ldap_session, target_samname, target_domain)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/share/pipx/venvs/pywhisker/lib/python3.12/site-packages/pywhisker/pywhisker.py", line 258, in __init__
    logger.debug('Initializing domainDumper()')
    ^^^^^^
NameError: name 'logger' is not defined. Did you mean: 'Logger'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/.local/bin/pywhisker", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/kali/.local/share/pipx/venvs/pywhisker/lib/python3.12/site-packages/pywhisker/pywhisker.py", line 839, in main
    logger.error(str(e))
  File "/home/kali/.local/share/pipx/venvs/pywhisker/lib/python3.12/site-packages/pywhisker/pywhisker.py", line 733, in error
    console.print("{}[!]{} {}".format("[bold red]", "[/bold red]", message), highlight=False)
    ^^^^^^^
NameError: name 'console' is not defined. Did you mean: 'Console'?
```

From git clone:

```
pywhisker -d example.com -u example_user -p example_pass --target example_target --action add

[!] name 'logger' is not defined
```

**Comment by b4keSn4ke** [comment]
I confirm that the same thing happened to me executing it from a venv

**Comment by KillingTree** [comment]
I also reproduced the error.

Seems like a scope problem on logger and console variable. 

logger definition was moved to main function while doing the pipx support but can't be found within ShadowCredentials execution. 

console is defined within `if __name__ = '__main':` so it's only available globally when executing as a standalone script and seems not working through pipx (like a module import). 

I'm not a python expert but I'll try to fix this and submit a PR in a more sophisticated way than just putting global in front of vars :')

**Comment by ShutdownRepo** [comment]
Should be fixed thanks to #24 
Please feel free to reopen if things don't work as they should 🙏
